### ISSUE TITLE
Program in Docker does not work properly

### ISSUE THREAD

**Issue by dtrinh100** [dtrinh100/Music-Playlist#15]
Two issues that I have found so far:

1. Go to the /register page and refresh, it doesn't refresh, it goes to a 404.

2. It's unable to make a call to the back-end. I suggest you look at how the code is called from my registration branch, then try to mimic those calls in Docker (my code will make a request to the back-end it just won't insert into a db, since a DB does not exist there).

**Comment by lovo-h** [comment]
For point #2, you have to change "localhost" to "0.0.0.0"

I'll look into point #1. That sounds really strange.

**Comment by dtrinh100** [comment]
Issue has now been resolved. It turned out to be a Caddy bug, lets use hash location for now until that issue is fixed.
