### ISSUE TITLE
Potential issue with cleaning up docker

### ISSUE THREAD

**Issue by dtrinh100** [dtrinh100/Music-Playlist#25]
When I am trying to clean up unused images, containers, etc. I get the following error:

> Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.30/containers/json: dial unix /var/run/docker.sock: connect: permission denied
> "docker kill" requires at least 1 argument(s).
> See 'docker kill --help'.

This is even after I run docker as a user.

**Comment by lovo-h** [comment]
What was the command that you ran?

**Comment by dtrinh100** [comment]
Any docker cleaning command causes an error that looks similar to this. For this one, I ran the docker kill command. I have also tried running this command: `docker volume rm $(docker volume ls -qf dangling=true)`. This could be an issue with my system, so I'll close it for now.
